apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywhatsapp.fullname" . }}-headless
  labels:
    {{- include "mywhatsapp.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "mywhatsapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 2785
      targetPort: http
